# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Anti-cheat-WIN10/Desktop/shiftLAR/shiftLAR.cache/wt [current_project]
set_property parent.project_path C:/Users/Anti-cheat-WIN10/Desktop/shiftLAR/shiftLAR.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/Anti-cheat-WIN10/Desktop/shiftLAR/shiftLAR.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Anti-cheat-WIN10/Desktop/shiftLAR/shiftLAR.srcs/sources_1/new/LFSR.v
  C:/Users/Anti-cheat-WIN10/Downloads/final.xpr/1/1.srcs/sources_1/imports/LAB4/RingCounter.v
  C:/Users/Anti-cheat-WIN10/Downloads/final.xpr/1/1.srcs/sources_1/imports/LAB4/Time_Counter.v
  C:/Users/Anti-cheat-WIN10/Desktop/shiftLAR/shiftLAR.srcs/sources_1/new/qsec_clks.v
  C:/Users/Anti-cheat-WIN10/Desktop/shiftLAR/shiftLAR.srcs/sources_1/new/TOPLED.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Anti-cheat-WIN10/Desktop/LAB4/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Anti-cheat-WIN10/Desktop/LAB4/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOPLED -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOPLED.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOPLED_utilization_synth.rpt -pb TOPLED_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
